title : Elementary - Jekyll Blog Theme
name: 'MY_recipes'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  posts:
    title: All posts
    default_open: false
    output: true
  aenv:
    title: environment setting
    default_open: false
    output: true
  bdata:
    title: data communication
    default_open: false
    output: true
  cserver:
    title: server
    default_open: false
    output: true
  dandroid:
    title: android
    default_open: false
    output: true
  eimage:
    title: image
    default_open: false
    output: true
  fgit:
    title: git
    default_open: false
    output: true
  gkernel:
    title: kernel
    default_open: false
    output: true
  hutil:
    title: util
    default_open: false
    output: true
  firmware:
    title: firmware
    default_open: false
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: posts
    values:
      title: environment setting
      permalink: /aenv/:title
  - scope:
      type: posts
    values:
      title: communication
      permalink: /bdata/:title
  - scope:
      type: posts
    values:
      title: server
      permalink: /cserver/:title
  - scope:
      type: posts
    values:
      title: android
      permalink: /dandroid/:title
  - scope:
      type: posts
    values:
      title: image
      permalink: /eimage/:title
  - scope:
      type: posts
    values:
      title: git
      permalink: /fgit/:title
  - scope:
      type: posts
    values:
      title: kernel
      permalink: /gkernel/:title
  - scope:
      type: posts
    values:
      title: util
      permalink: /hutil/:title
  - scope:
      type: posts
    values:
      title: firmware
      permalink: /firmware/:title
      
      
plugins:
  - jekyll-sitemap
