title : Elementary - Jekyll Blog Theme
name: 'MY_recipes'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  posts:
    title: All posts
    default_open: false
    output: true
  arm_architecture:
    title: arm architecture
    default_open: false
    output: true
  blinux_kernel:
    title: linux kernel
    default_open: false
    output: true
  cdevice_driver:
    title: device driver
    default_open: false
    output: true


defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: posts
    values:
      title: arm architecture
      permalink: /arm_architecture/:title
  - scope:
      type: posts
    values:
      title: linux kernel
      permalink: /blinux_kernel/:title
  - scope:
      type: posts
    values:
      title: device driver
      permalink: /cdevice_driver/:title


plugins:
  - jekyll-sitemap
