title : Elementary - Jekyll Blog Theme
name: 'MY_recipes'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true



featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  workskill:
    title: skill
    default_open: false
    output: true
  hardware:
    title: hardware
    default_open: false
    output: true
  kernel:
    title: kernel
    default_open: false
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: skill
      permalink: /workskill/:title
  - scope:
      type: posts
    values:
      title: hardware
      permalink: /hardware/:title
  - scope:
      type: posts
    values:
      title: kernel
      permalink: /kernel/:title
      
plugins:
  - jekyll-sitemap
